# Generated by Django 2.2 on 2020-07-26 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poll',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
